### ISSUE TITLE
Weird CSS/Class Issue w/`alwaysOpen: true` + `staticList: true`

### ISSUE THREAD

**Issue by ForbiddenEra** [dipson88/treeselectjs#94]
With `alwaysOpen: true` + `staticList: true` the list shows up as expected and initially, the list has the `treeselect-input--bottom` class, however when you click out of the component, that class switches to `treeselect-input--top` and doesn't return to `treeselect-input--bottom` when re-focusing, though I'm not sure if it should've really changed at all when `alwaysOpen`+`static`.

This causes the borders to go a little wonky, losing the top border completely after de-focusing.

As a workaround I've just commented the original `treeselect-input--top` definition and added the class to the `treeselect-input--bottom` definition:

```css
// .treeselect-input--opened.treeselect-input--top{border-top-color:transparent;border-top-left-radius:0;border-top-right-radius:0}
.treeselect-input--opened.treeselect-input--top,
.treeselect-input--opened.treeselect-input--bottom{border-bottom-color:transparent;border-bottom-left-radius:0;border-bottom-right-radius:0}
```
